### ISSUE TITLE
Additional RSVP imports

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-rfc176-data#13] opened 2017-07-06 09:31 UTC
Right now it is only possible to

```js
import RSVP from 'rsvp';
```

but to get to `Promise` or `resolve()` it is not possible to

```js
import { Promise, resolve } from 'rsvp';
```

IMHO we should change that

**Comment by locks** [comment] 2017-07-06 10:29
Not a bad idea, indeed.

**Comment by rwjblue** [comment] 2017-07-06 11:46
Seems like a dupe of https://github.com/ember-cli/ember-cli-shims/pull/67 which @stefanpenner opposed :confused:

**Comment by cibernox** [comment] 2017-07-07 16:10
FWIW, I think that it makes sense to expose `Promise` directly, without destructuring RSVP. However, since `Promise.resolve` is part of the spec, I don't see the case for `RSVP.resolve`, unless there is some subtle difference I'm not aware of.

**Comment by rwjblue** [comment] 2017-07-08 20:02
Some of this is done, but as I mentioned in #18 we should likely bring in a few more named exports here.

**Closed** 2017-07-09 12:49 UTC
Labels: enhancement
